### ISSUE TITLE
Provided download link not working

### ISSUE THREAD

**Issue by asifzamil** [bitnol/CipherAPI#2]
Dear this script provides the link like:
http://r5---sn-nwj7kne6.googlevideo.com/videoplayback?mm=31&upn=kifQUh3nuNw&id=o-AEr-0fHrwgidqFuX2op-54pB6iBycZP1aW0bnHpiTqs_&dur=182.903&gcr=us&initcwndbps=828750&ip=198.57.247.235&key=yt5&fexp=900718%2C927622%2C927882%2C932404%2C9405179%2C9405763%2C943917%2C947209%2C947218%2C948124%2C952302%2C952605%2C952901%2C955301%2C957103%2C957105%2C957201&source=youtube&mv=m&mt=1419333281&ms=au&ratebypass=yes&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cratebypass%2Csource%2Cupn%2Cexpire&ipbits=0&expire=1419354911&itag=22&sver=3&mime=video%2Fmp4&signature=3BDE62DB8406E0FA760D215E42966BDF3D9B3CD0.2F1074474AA82AEE2977C35A1387952CB17F54E1
which don't download videos how to convert it link like this:
http://r5---sn-aigllnzk.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?id=o-AIcwAOzyxsnB3m6fp-BT7RWdyUfQcbAj-Nwq900pYoNw&mm=31&ms=au&mv=m&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cnh%2Cratebypass%2Csource%2Cupn%2Cexpire&mt=1419333890&ip=2a03%3Ab0c0%3A1%3Ad0%3A%3A24a%3A7001&source=youtube&upn=tNi9SStpOO4&initcwndbps=11808750&itag=18&key=yt5&mime=video%2Fmp4&nh=IgpwcjAzLmxocjE0KgkxMjcuMC4wLjE&fexp=900718%2C924628%2C927622%2C932404%2C936928%2C941004%2C943917%2C947209%2C947218%2C948124%2C952302%2C952605%2C952901%2C955301%2C955405%2C957103%2C957105%2C957201%2C959701%2C960604&expire=1419355508&ratebypass=yes&sver=3&dur=182.903&ipbits=0&gcr=us&signature=D675A05A4CFAFBBE282AC50ABAB8DECE74705AF9.F34796704F8B611537908FA7852EC79BC1C2D9D2&title=
2nd code is working but how to generate links like this?

**Comment by badershs** [comment]
i have problem in the first it was working 
but today suddenly it's not working and  i dont know why 
its work on my localhost but it's not on the server

**Comment by bitnol** [comment]
What's the result you getting in your server?

**Comment by badershs** [comment]
now it's work 

the error was " Undefined index: status in /var/www/..."
but i'm sur the problem not from me because it was working on localhost but it's not on my server 

now every thing is ok

**Comment by badershs** [comment]
it's not working again -_- please can you check the problem  again ? ? ?  i think the problem from api 

'Unable to get Video Info"

**Comment by bitnol** [comment]
This issue is not related to the code. I think your IP has been blocked by Youtube due to excessive calls. To confirm it plez check the server logs. I suggest to use random IPs, any proxy or IPv6.

**Comment by badershs** [comment]
i think it's some thing not related to blocking 
because it's working now 
i didn't understand any thing :p

**Comment by bitnol** [comment]
closing for now, will check if it's replicable
